env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: "default"
    main: ./cmd/gutenfmt
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X internal/build.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - builds:
      - default
    format: binary
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
