version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: ./cmd/gutenfmt/
    flags:
      - -buildvcs
      - -trimpath
    targets:
      - darwin_arm64
      - linux_amd64
      - windows_amd64

archives:
  - id: default
    formats: [ binary ]
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{- .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
